#
# Copyright (c) 2020-2021 Huawei Device Co., Ltd.
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
#

obj-$(CONFIG_DRIVERS_HDF_PLATFORM)           += common/
obj-$(CONFIG_DRIVERS_HDF_PLATFORM_MIPI_DSI)  += mipi_dsi/
obj-$(CONFIG_DRIVERS_HDF_PLATFORM_GPIO)      += gpio/
obj-$(CONFIG_DRIVERS_HDF_PLATFORM_I2C)       += i2c/
obj-$(CONFIG_DRIVERS_HDF_PLATFORM_WATCHDOG)  += watchdog/
obj-$(CONFIG_DRIVERS_HDF_PLATFORM_PWM)       += pwm/
obj-$(CONFIG_DRIVERS_HDF_PLATFORM_UART)      += uart/
obj-$(CONFIG_DRIVERS_HDF_PLATFORM_MMC)       += mmc/
obj-$(CONFIG_DRIVERS_HDF_PLATFORM_SDIO)      += sdio/
obj-$(CONFIG_DRIVERS_HDF_PLATFORM_EMMC)      += emmc/
obj-$(CONFIG_DRIVERS_HDF_PLATFORM_SPI)       += spi/
obj-$(CONFIG_DRIVERS_HDF_PLATFORM_RTC)       += rtc/
