#
# Copyright (c) 2020-2021 Huawei Device Co., Ltd.
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
#

obj-y  += ../../../../framework/ability/config/device_resource_if.o \
          ../../../../framework/ability/config/hcs_parser/src/hcs_blob_if.o \
          ../../../../framework/ability/config/hcs_parser/src/hcs_generate_tree.o \
          ../../../../framework/ability/config/hcs_parser/src/hcs_parser.o \
          ../../../../framework/ability/config/hcs_parser/src/hcs_tree_if.o
ccflags-y += -Iinclude/hdf \
             -Iinclude/hdf/osal \
             -Iinclude/hdf/utils \
             -Idrivers/hdf/khdf/osal/include \
             -Idrivers/hdf/framework/include \
             -Idrivers/hdf/framework/include/utils \
             -Idrivers/hdf/framework/include/config \
             -Idrivers/hdf/framework/ability/config/hcs_parser/include
