
obj-$(CONFIG_DRIVERS_HDF_USB_F_GENERIC) += f_generic.o

ccflags-y += -lm -lc -lgcc \
             -Idrivers/hdf/framework/include/utils \
             -Idrivers/hdf/khdf/osal/include \
             -Idrivers/hdf/framework/include/core \
             -Idrivers/hdf/framework/core/common/include/host \
             -Idrivers/hdf/framework/ability/sbuf/include \
             -Idrivers/hdf/../../../../../../../../../../../../../third_party/bounds_checking_function/include \
             -Idrivers/hdf/framework/include \
             -Idrivers/hdf/framework/include/osal \
             -Idrivers/hdf/framework/include/platform \
             -Idrivers/hdf/framework/include/config \
             -I$(PROJECT_ROOT)/third_party/bounds_checking_function/include

